import {Category} from '../src/categories'

export interface Animal {
    id: number;
    kind_of_animal: string;
    breed_of_animal: string;
    name: string;
    age: number;
    description: string;
    imageUrl: string;
    category: Category;
  }

export const animals = [
        {
          id: 1,
          kind_of_animal: "Cat",
          breed_of_animal: "Siamese",
          name: "Mittens",
          age: 3,
          description: "Playful and affectionate, enjoys chasing toys.",
          imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Siam_lilacpoint.jpg/800px-Siam_lilacpoint.jpg",
          category: { name: "Animals" },
        },
        {
          id: 2,
          kind_of_animal: "Dog",
          breed_of_animal: "Golden Retriever",
          name: "Max",
          age: 2,
          description: "Friendly and loyal, loves being around people.",
          imageUrl: "https://vgl.ucdavis.edu/sites/g/files/dgvnsk15116/files/media/images/Golden-Retriever-600px.jpg",
          category: { name: "Animals" },
        },
        {
          id: 3,
          kind_of_animal: "Cat",
          breed_of_animal: "Maine Coon",
          name: "Fluffy",
          age: 4,
          description: "Gentle giant, enjoys lounging and bird-watching.",
          imageUrl: "https://i.redd.it/ixxwnw3ywreb1.jpg",
          category: { name: "Animals" },
        },
        {
          id: 4,
          kind_of_animal: "Dog",
          breed_of_animal: "Poodle",
          name: "Bella",
          age: 1,
          description: "Intelligent and playful, a quick learner.",
          imageUrl: "https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-09/Poodle%20toy.jpg?h=1c913292&itok=JseYEq5R",
          category: { name: "Animals" },
        },
        {
          id: 5,
          kind_of_animal: "Cat",
          breed_of_animal: "Bengal",
          name: "Leo",
          age: 2,
          description: "Energetic and curious, loves climbing and exploring.",
          imageUrl: "https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-06/Bengal-Cat.jpg?itok=-n4U6Hsa",
          category: { name: "Animals" },
        },
        {
          id: 6,
          kind_of_animal: "Dog",
          breed_of_animal: "Siberian Husky",
          name: "Luna",
          age: 3,
          description: "Energetic and friendly, with striking blue eyes.",
          imageUrl: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwagwalking.com%2Fdaily%2F8-awesome-siberian-husky-facts&psig=AOvVaw1rhIjFgw8iyxCpZuf4xEkF&ust=1709310828896000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCJjbuZj90IQDFQAAAAAdAAAAABAD",
          category: { name: "Animals" },
        },
        {
          id: 7,
          kind_of_animal: "Cat",
          breed_of_animal: "Ragdoll",
          name: "Whiskers",
          age: 5,
          description: "Relaxed and docile, enjoys being cradled like a baby.",
          imageUrl: "https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-06/Ragdoll.jpg?itok=uoJljrty",
          category: { name: "Animals" },
        },
        {
          id: 8,
          kind_of_animal: "Dog",
          breed_of_animal: "Beagle",
          name: "Charlie",
          age: 4,
          description: "Curious and friendly, excellent sense of smell.",
          imageUrl: "https://www.akc.org/wp-content/uploads/2021/01/Beagle-puppy-standing-in-the-grass-1-500x486.jpeg",
          category: { name: "Animals" },
        },
        {
          id: 9,
          kind_of_animal: "Cat",
          breed_of_animal: "Scottish Fold",
          name: "Oliver",
          age: 3,
          description: "Sweet and gentle, with distinctive folded ears.",
          imageUrl: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fscottishfold%2Fcomments%2F127uk1c%2Fmy_60_days_old_girl_nina_scottish_fold_dad%2F&psig=AOvVaw0qqwMXuGu5RwDx7xlACFPR&ust=1709310874328000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLCS4K790IQDFQAAAAAdAAAAABAD",
          category: { name: "Animals" },
        },
        {
          id: 10,
          kind_of_animal: "Dog",
          breed_of_animal: "Boxer",
          name: "Rocky",
          age: 2,
          description: "Playful and energetic, great with kids.",
          imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Male_fawn_Boxer_undocked.jpg",
          category: { name: "Animals" },
        },
        {
          id: 11,
          kind_of_animal: "Cat",
          breed_of_animal: "Persian",
          name: "Princess",
          age: 4,
          description: "Regal and calm, enjoys lounging in luxurious spots.",
          imageUrl: "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-106887540-e1698110433562.jpg?resize=1200,630",
          category: { name: "Animals" },
        },
        {
          id: 12,
          kind_of_animal: "Dog",
          breed_of_animal: "Dachshund",
          name: "Coco",
          age: 3,
          description: "Lively and affectionate, with a distinctive long body.",
          imageUrl: "https://dogtime.com/wp-content/uploads/sites/12/2011/01/GettyImages-700141990-e1688418771301.jpg?w=1024",
          category: { name: "Animals" },
        },
        {
          id: 13,
          kind_of_animal: "Cat",
          breed_of_animal: "Sphynx",
          name: "Nala",
          age: 2,
          description: "Hairless and warm, enjoys cuddling for warmth.",
          imageUrl: "https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-06/Sphynx.jpg?itok=XRBkheYL",
          category: { name: "Animals" },
        },
        {
          id: 14,
          kind_of_animal: "Dog",
          breed_of_animal: "Shih Tzu",
          name: "Milo",
          age: 1,
          description: "Charming and playful, with a silky coat.",
          imageUrl: "https://www.orchardroadanimalhospital.com/sites/default/files/styles/large/public/shih-tzu-dog-breed-info.jpg?itok=CwWMOPs2",
          category: { name: "Animals" },
        },
        {
          id: 15,
          kind_of_animal: "Cat",
          breed_of_animal: "Abyssinian",
          name: "Shadow",
          age: 3,
          description: "Active and social, loves climbing and jumping.",
          imageUrl: "https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-06/Abyssinian-Cat-Breed_0.jpg?itok=r3GCHbzx",
          category: { name: "Animals" },
        },
        {
          id: 16,
          kind_of_animal: "Dog",
          breed_of_animal: "Rottweiler",
          name: "Thor",
          age: 4,
          description: "Strong and protective, a loyal companion.",
          imageUrl: "https://www.akc.org/wp-content/uploads/2017/11/Rottweiler-On-White-10.jpg",
          category: { name: "Animals" },
        },
        {
          id: 17,
          kind_of_animal: "Cat",
          breed_of_animal: "British Shorthair",
          name: "Whiskey",
          age: 2,
          description: "Calm and easygoing, with a plush coat.",
          imageUrl: "https://www.purina.co.nz/sites/default/files/2021-02/CAT%20HERO_0004_British_shorthair.jpg",
          category: { name: "Animals" },
        },
        {
          id: 18,
          kind_of_animal: "Dog",
          breed_of_animal: "Cavalier King Charles Spaniel",
          name: "Bentley",
          age: 3,
          description: "Gentle and affectionate, enjoys snuggling.",
          imageUrl: "https://cdn.shopify.com/s/files/1/2993/4600/files/a_Stock_image_of_a_Cavalier_King_Charles_Spaniel_-_BigPawShop.ca_2435a2ed-4c55-43c1-8310-103f7e81d20e_600x600.png?v=1683087882",
          category: { name: "Animals" },
        },
        {
          id: 19,
          kind_of_animal: "Cat",
          breed_of_animal: "Egyptian Mau",
          name: "Cleo",
          age: 1,
          description: "Spotted beauty, playful and curious.",
          imageUrl: "https://www.purina.co.nz/sites/default/files/styles/ttt_image_510/public/2021-02/CAT%20BREED%20Hero%20Mobile_0029_Egyptian_mau.jpg?itok=DDoH95Qv",
          category: { name: "Animals" },
        },
        {
          id: 20,
          kind_of_animal: "Dog",
          breed_of_animal: "Doberman Pinscher",
          name: "Zeus",
          age: 2,
          description: "Energetic and intelligent, a natural protector.",
          imageUrl: "https://www.purina.co.nz/sites/default/files/styles/ttt_image_510/public/2021-02/BREED%20Hero%20Mobile_0067_miniature_pinscher.jpg?itok=TlQjhfbs",
          category: { name: "Animals" },
        }
      
]